[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ua-nemo"
version = "0.2.0"
description = "Parses nodeset XML files and resolves relations. "
readme = "README.md"
authors= [{name = "Andreas Engh Halvorsen"}]
requires-python = ">=3.10"
dependencies = [
    "lxml",
]
[project.optional-dependencies]
memory-profiling = [
    "memray>=1.10",
    "pytest-memray>=1.5"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src", "."]
markers = [
    "memory_profile: tests for memory profiling",
]

[tool.setuptools.package-data]
ua_nemo = [
    "typelibraries/**/*"
]